version: "3.9"

services:
  transcriber:
    container_name: video-transcriber
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ${SSH_PRIVATE_KEY_PATH}:${PRIVATE_KEY_PATH}:ro
      - ${MODEL_HOST_PATH}:${MODEL_PATH}
#      - ${TORCH_CACHE_DIR_HOST}:${TORCH_CACHE_DIR}
      - ${REMOTE_AUDIO_DIRS}:/app/audios
      - ${REMOTE_VIDEO_DIRS}:/app/videos
      - ${REMOTE_TRANSCRIPT_DIR}:/app/text_transcripts
    restart: unless-stopped
